name: check-branch-name
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch naming (feature/* or fix/*)
        run: |
          BRANCH="${{ github.head_ref }}"
          if [[ ! "$BRANCH" =~ ^(feature|fix)\/[a-z0-9._-]+$ ]]; then
            echo "❌ Branch '$BRANCH' no cumple con el naming. Use 'feature/*' o 'fix/*'."
            exit 1
          fi
